#!/bin/zsh

if [ ! -d results ]; then mkdir results; fi
DATE=$(date '+%F-%s')
racket test-all-grammars.rkt >& results/master-$DATE.log
COMMIT_HASH=$(git rev-parse --short --verify HEAD)
git log --decorate 'HEAD^..HEAD' > results/commit-$COMMIT_HASH-$DATE
