#lang racket

(require "../../../pda-to-pda-risc/macro-glue.rkt")

(provide (all-defined-out))

(define arithmetic-pda-risc
  (pda->pda-risc
   (TOKENS NUM L-PAREN R-PAREN TIMES DIVIDE PLUS MINUS *EOF*)
   (EOS *EOF*)
   (START s0)
   (RULE r1 *start () #f)
   (RULE r2 exp (NUM) NUM)
   (RULE r3 exp (exp-1 PLUS exp-2) (+ exp-1 exp-2))
   (RULE r4 exp (exp-1 MINUS exp-2) (- exp-1 exp-2))
   (RULE r5 exp (expA TIMES expB) (* expA expB))
   (RULE r6 exp (expA DIVIDE exp) (quotient expA exp))
   (RULE r7 exp (L-PAREN exp R-PAREN) exp)
   (STATE s0
          (COMMENT exp "=>" "." L-PAREN exp R-PAREN)
          (COMMENT exp "=>" "." exp DIVIDE exp)
          (COMMENT exp "=>" "." exp TIMES exp)
          (COMMENT exp "=>" "." exp MINUS exp)
          (COMMENT exp "=>" "." exp PLUS exp)
          (COMMENT exp "=>" "." NUM)
          (COMMENT *start "=>" "." exp *EOF*)
          (SHIFT (NUM) s2)
          (SHIFT (L-PAREN) s3)
          (GOTO exp s1))
   (STATE s1
          (COMMENT exp "=>" exp "." DIVIDE exp)
          (COMMENT exp "=>" exp "." TIMES exp)
          (COMMENT exp "=>" exp "." MINUS exp)
          (COMMENT exp "=>" exp "." PLUS exp)
          (COMMENT *start "=>" exp "." *EOF*)
          (SHIFT (TIMES) s6)
          (SHIFT (DIVIDE) s7)
          (SHIFT (PLUS) s8)
          (SHIFT (MINUS) s9)
          (ACCEPT (*EOF*)))
   (STATE s2
          (COMMENT exp "=>" NUM ".")
          (REDUCE () r2))
   (STATE s3
          (COMMENT exp "=>" L-PAREN "." exp R-PAREN)
          (COMMENT exp "=>" "." L-PAREN exp R-PAREN)
          (COMMENT exp "=>" "." exp DIVIDE exp)
          (COMMENT exp "=>" "." exp TIMES exp)
          (COMMENT exp "=>" "." exp MINUS exp)
          (COMMENT exp "=>" "." exp PLUS exp)
          (COMMENT exp "=>" "." NUM)
          (SHIFT (NUM) s2)
          (SHIFT (L-PAREN) s3)
          (GOTO exp s4))
   (STATE s4
          (COMMENT exp "=>" L-PAREN exp "." R-PAREN)
          (COMMENT exp "=>" exp "." DIVIDE exp)
          (COMMENT exp "=>" exp "." TIMES exp)
          (COMMENT exp "=>" exp "." MINUS exp)
          (COMMENT exp "=>" exp "." PLUS exp)
          (SHIFT (R-PAREN) s5)
          (SHIFT (TIMES) s6)
          (SHIFT (DIVIDE) s7)
          (SHIFT (PLUS) s8)
          (SHIFT (MINUS) s9))
   (STATE s5
          (COMMENT exp "=>" L-PAREN exp R-PAREN ".")
          (REDUCE () r7))
   (STATE s6
          (COMMENT exp "=>" "." L-PAREN exp R-PAREN)
          (COMMENT exp "=>" "." exp DIVIDE exp)
          (COMMENT exp "=>" exp TIMES "." exp)
          (COMMENT exp "=>" "." exp TIMES exp)
          (COMMENT exp "=>" "." exp MINUS exp)
          (COMMENT exp "=>" "." exp PLUS exp)
          (COMMENT exp "=>" "." NUM)
          (SHIFT (NUM) s2)
          (SHIFT (L-PAREN) s3)
          (GOTO exp s13))
   (STATE s7
          (COMMENT exp "=>" "." L-PAREN exp R-PAREN)
          (COMMENT exp "=>" exp DIVIDE "." exp)
          (COMMENT exp "=>" "." exp DIVIDE exp)
          (COMMENT exp "=>" "." exp TIMES exp)
          (COMMENT exp "=>" "." exp MINUS exp)
          (COMMENT exp "=>" "." exp PLUS exp)
          (COMMENT exp "=>" "." NUM)
          (SHIFT (NUM) s2)
          (SHIFT (L-PAREN) s3)
          (GOTO exp s12))
   (STATE s8
          (COMMENT exp "=>" "." L-PAREN exp R-PAREN)
          (COMMENT exp "=>" "." exp DIVIDE exp)
          (COMMENT exp "=>" "." exp TIMES exp)
          (COMMENT exp "=>" "." exp MINUS exp)
          (COMMENT exp "=>" exp PLUS "." exp)
          (COMMENT exp "=>" "." exp PLUS exp)
          (COMMENT exp "=>" "." NUM)
          (SHIFT (NUM) s2)
          (SHIFT (L-PAREN) s3)
          (GOTO exp s11))
   (STATE s9
          (COMMENT exp "=>" "." L-PAREN exp R-PAREN)
          (COMMENT exp "=>" "." exp DIVIDE exp)
          (COMMENT exp "=>" "." exp TIMES exp)
          (COMMENT exp "=>" exp MINUS "." exp)
          (COMMENT exp "=>" "." exp MINUS exp)
          (COMMENT exp "=>" "." exp PLUS exp)
          (COMMENT exp "=>" "." NUM)
          (SHIFT (NUM) s2)
          (SHIFT (L-PAREN) s3)
          (GOTO exp s10))
   (STATE s10
          (COMMENT exp "=>" exp "." DIVIDE exp)
          (COMMENT exp "=>" exp "." TIMES exp)
          (COMMENT exp "=>" exp MINUS exp ".")
          (COMMENT exp "=>" exp "." MINUS exp)
          (COMMENT exp "=>" exp "." PLUS exp)
          (REDUCE (R-PAREN) r4)
          (SHIFT (TIMES) s6)
          (SHIFT (DIVIDE) s7)
          (REDUCE (PLUS) r4)
          (REDUCE (MINUS) r4)
          (REDUCE (*EOF*) r4))
   (STATE s11
          (COMMENT exp "=>" exp "." DIVIDE exp)
          (COMMENT exp "=>" exp "." TIMES exp)
          (COMMENT exp "=>" exp "." MINUS exp)
          (COMMENT exp "=>" exp PLUS exp ".")
          (COMMENT exp "=>" exp "." PLUS exp)
          (REDUCE (R-PAREN) r3)
          (SHIFT (TIMES) s6)
          (SHIFT (DIVIDE) s7)
          (REDUCE (PLUS) r3)
          (REDUCE (MINUS) r3)
          (REDUCE (*EOF*) r3))
   (STATE s12
          (COMMENT exp "=>" exp DIVIDE exp ".")
          (COMMENT exp "=>" exp "." DIVIDE exp)
          (COMMENT exp "=>" exp "." TIMES exp)
          (COMMENT exp "=>" exp "." MINUS exp)
          (COMMENT exp "=>" exp "." PLUS exp)
          (REDUCE (R-PAREN) r6)
          (REDUCE (TIMES) r6)
          (REDUCE (DIVIDE) r6)
          (REDUCE (PLUS) r6)
          (REDUCE (MINUS) r6)
          (REDUCE (*EOF*) r6))
   (STATE s13
          (COMMENT exp "=>" exp "." DIVIDE exp)
          (COMMENT exp "=>" exp TIMES exp ".")
          (COMMENT exp "=>" exp "." TIMES exp)
          (COMMENT exp "=>" exp "." MINUS exp)
          (COMMENT exp "=>" exp "." PLUS exp)
          (REDUCE (R-PAREN) r5)
          (REDUCE (TIMES) r5)
          (REDUCE (DIVIDE) r5)
          (REDUCE (PLUS) r5)
          (REDUCE (MINUS) r5)
          (REDUCE (*EOF*) r5))
   (STATE s14
          (COMMENT *start "=>" exp *EOF* ".")
          (REDUCE () r1))))
